name: ci

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:

env:
  JAVA_VERSION: "17"
  MAVEN_ARGS: "-B -ntp -f docs/ci/pom-ci.xml"

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ env.JAVA_VERSION }}"
          cache: "maven"

      - name: Build and test (full reactor)
        run: mvn ${{ env.MAVEN_ARGS }} test

  sonar:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ env.JAVA_VERSION }}"
          cache: "maven"

      - name: Sonar scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn ${{ env.MAVEN_ARGS }} -Dsonar.login=$SONAR_TOKEN sonar:sonar

  release:
    runs-on: ubuntu-latest
    needs: build_test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ env.JAVA_VERSION }}"
          cache: "maven"

      - name: Set version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          mvn ${{ env.MAVEN_ARGS }} versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

      - name: Package runtime (app)
        run: mvn ${{ env.MAVEN_ARGS }} -pl app -am package

      - name: Publish artifacts to Maven repo
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: mvn ${{ env.MAVEN_ARGS }} deploy -DskipTests

      # Exemplo de publicacao em servico de nuvem (ajuste conforme o provedor)
      - name: Publish artifact to S3 (example)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 cp app/target/app-*.jar s3://my-bucket/mmvsms/releases/
